version: '3.4'
services:
  coreweb:
    image: ${DOCKER_REGISTRY-}webfrontend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__MusicStoreEntities=Server=db;Initial Catalog=MusicStore;User Id=sa;Password=P@ssword1
      - ConnectionStrings__IdentityConnection=Server=db;Initial Catalog=identity;User Id=sa;Password=P@ssword1
      - ConnectionStrings__redisConnection=redis:6379
    ports:
      - "80"
    depends_on:
      - db
      - redis
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "P@ssword1"
      ACCEPT_EULA: "Y"
    ports:
      - "1601:1433"
  redis:
    image: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy.conf:/etc/nginx/proxy.conf:ro
    depends_on:
      - coreweb
    ports:
      - "5000:5000"
